version: '3'

services:
  neo4j:
    image: neo4j:5.15.0
    container_name: neo4j-db
    ports:
      - "7474:7474"  
      - "7473:7473"  
      - "7687:7687"  
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  swift-code-api:
    build: .
    container_name: swift-code-api
    ports:
      - "8080:8080"
    volumes:
      - ./banks.csv:/app/banks.csv
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - CSV_FILE_PATH=/app/banks.csv
      - IMPORT_CSV_ON_STARTUP=true
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

volumes:
  neo4j_data: